### ISSUE TITLE
Seeing operation_timeout errors on first use

### ISSUE THREAD

**Issue by mikeyrcamp** [f3peakcity/f3_bot#9]
Need to profile this to see what is up, but a retry always fixes it which makes me believe it is startup lag with GCP. Slack expects an API response within 5 seconds of the initial request so we need to figure out how to make this response as quickly as possible. I've seen solutions on stackoverflow where folks open the dialog, and then follow it with an update.

**Comment by mrhubbell** [comment]
Is it worth an @channel post in 1stF so everyone is aware?

**Comment by mikeyrcamp** [comment]
Probably cold starts. Thought this article was interesting. https://medium.com/google-cloud/serverless-performance-comparison-does-the-language-matter-c72a7191c799

**Comment by mikeyrcamp** [comment]
> Is it worth an @channel post in 1stF so everyone is aware?

@mrhubbell good point I'll make a post about it.

**Comment by mikeyrcamp** [comment]
@jcampbell resolved this earlier this year, closing.
